import * as cheerio from 'cheerio';
import {createClient} from '@supabase/supabase-js';
export const revalidate=86400;
const WIKI='https://en.wikipedia.org/wiki/List_of_Star_Trek_novels';
const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL||'https://bqktykhknaeuuycquqns.supabase.co';
const SUPABASE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_LiwJ6jgLNx8_ZUCHEbJW5g_1WjXFZZQ';
const clean=s=>String(s||'').replace(/\[[^\]]*\]$/g,'').replace(/[†‡◊#≈]+/g,'').replace(/\s+/g,' ').trim();
const year=s=>{const m=String(s||'').match(/\b(?:19|20)\d{2}\b/);return m?Number(m[0]):null};
const isbnOf=s=>{const m=String(s||'').match(/\b(?:97[89][- ]?)?\d(?:[- ]?\d){8,12}[Xx]?\b/);return m?m[0]:''};
const badAuthor=s=>!s||/^(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\b/i.test(s)||/^\d{4}$/.test(s)||!!isbnOf(s)||/^[A-Z]{1,3}\d{3,5}$/.test(s)||/^[-—]$/.test(s);
function expandTable($,table){let active=new Map();const grid=[];$(table).find('tr').each((_,tr)=>{const prev=active;active=new Map();const cells=[];let ci=0;const consume=()=>{const sp=prev.get(ci);if(!sp)return false;cells[ci]=sp.value;if(sp.left>1)active.set(ci,{value:sp.value,left:sp.left-1});ci++;return true};$(tr).children('th,td').each((_,cell)=>{while(consume()){}const value=clean($(cell).text()),rs=Math.max(1,Number($(cell).attr('rowspan')||1)),cs=Math.max(1,Number($(cell).attr('colspan')||1));for(let k=0;k<cs;k++){cells[ci+k]=value;if(rs>1)active.set(ci+k,{value,left:rs-1})}ci+=cs});const maxPrev=Math.max(-1,...prev.keys());while(ci<=maxPrev){if(!consume())ci++}grid.push(cells)});return grid}
function tableRows($,table,section){const grid=expandTable($,table);if(grid.length<2)return[];const hi=grid.findIndex(r=>r.some(v=>/title|name/i.test(clean(v)))&&r.some(v=>/author|writer|editor|date|published|publication/i.test(clean(v))));if(hi<0)return[];const headers=grid[hi].map(x=>clean(x).toLowerCase());const idx=re=>headers.findIndex(h=>re.test(h));const ti=idx(/title|name/),ai=idx(/author|writer|editor/),di=idx(/date|published|publication/),ii=idx(/isbn|catalog/),ni=idx(/^no\.?$|number|book\s*no/);if(ti<0)return[];return grid.slice(hi+1).map(r=>{const title=clean(r[ti]);if(!title||/^(title|name)$/i.test(title))return null;let author=ai>=0?clean(r[ai]):'',date=di>=0?clean(r[di]):'',isbn=ii>=0?isbnOf(clean(r[ii])):'';if(badAuthor(author))author='';if(!date){const d=r.map(clean).find(v=>year(v));if(d)date=d}if(!isbn){const x=r.map(clean).map(isbnOf).find(Boolean);if(x)isbn=x}const number=ni>=0?Number((clean(r[ni]).match(/^\s*(\d{1,3})\s*$/)||[])[1]||0)||null:null;return{title,author,series:section,number,publicationYear:year(date),isbn}}).filter(Boolean)}
export async function GET(){try{const res=await fetch(WIKI,{headers:{'User-Agent':'StarTrekBooks/1.0'},next:{revalidate:86400}});if(!res.ok)throw new Error(`Wikipedia ${res.status}`);const html=await res.text(),$=cheerio.load(html),books=[];let section='Uncategorised';$('h2,h3,h4,table.wikitable').each((_,el)=>{const tag=(el.tagName||el.name||'').toLowerCase();if(/^h[234]$/.test(tag)){const t=clean($(el).text());if(t)section=t.replace(/\[edit\]$/i,'').trim()||section;return}books.push(...tableRows($,el,section))});const unique=new Map();for(const b of books){const k=`${b.title.toLowerCase()}|${(b.author||'').toLowerCase()}|${b.publicationYear||''}`;if(!unique.has(k))unique.set(k,b)}let result=[...unique.values()];const sb=createClient(SUPABASE_URL,SUPABASE_KEY);const{data}=await sb.from('goodreads_metadata').select('book_key,goodreads_url,goodreads_rating,goodreads_ratings,fetched_at');const gm=new Map((data||[]).map(x=>[x.book_key,x]));result=result.map(b=>{const k=`${b.title.trim()}|${(b.author||'').trim()}|${b.publicationYear||''}`.toLowerCase(),m=gm.get(k);return{...b,goodreadsUrl:m?.goodreads_url||null,goodreadsRating:m?.goodreads_rating==null?null:Number(m.goodreads_rating),goodreadsRatings:m?.goodreads_ratings??null,goodreadsFetchedAt:m?.fetched_at||null}});return Response.json({books:result,count:result.length,source:'Wikipedia + cached Goodreads metadata'})}catch(e){return Response.json({books:[],count:0,error:e.message},{status:500})}}
