import * as cheerio from 'cheerio';
import {createClient} from '@supabase/supabase-js';
export const revalidate=86400;
const WIKI='https://en.wikipedia.org/wiki/List_of_Star_Trek_novels';
const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL||'https://bqktykhknaeuuycquqns.supabase.co';
const SUPABASE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_LiwJ6jgLNx8_ZUCHEbJW5g_1WjXFZZQ';
const clean=s=>String(s||'').replace(/\[[^\]]*\]$/g,'').replace(/[†‡◊#≈]+/g,'').replace(/\s+/g,' ').trim();
const year=s=>{const m=String(s||'').match(/\b(?:19|20)\d{2}\b/);return m?Number(m[0]):null};
const badAuthor=s=>!s||/^(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\b/i.test(s)||/^\d{4}$/.test(s)||/^(?:97[89][- ]?)?\d[- 0-9Xx]{8,}$/.test(s);
function tableRows($,table,section){const grid=[],spans={};$(table).find('tr').each((ri,tr)=>{const cells=[];let ci=0;while(spans[ci]){cells[ci]=spans[ci].value;if(--spans[ci].left<=0)delete spans[ci];ci++}$(tr).children('th,td').each((_,cell)=>{while(cells[ci]!==undefined)ci++;const value=clean($(cell).text()),rs=Number($(cell).attr('rowspan')||1),cs=Number($(cell).attr('colspan')||1);for(let k=0;k<cs;k++){cells[ci+k]=value;if(rs>1)spans[ci+k]={value,left:rs-1}}ci+=cs});grid.push(cells)});if(grid.length<2)return[];const headers=grid[0].map(x=>clean(x).toLowerCase());const idx=re=>headers.findIndex(h=>re.test(h));const ti=idx(/title|name/),ai=idx(/author|writer|editor/),di=idx(/date|published|publication/),ii=idx(/isbn|catalog/),ni=idx(/no\.|number|book/);if(ti<0)return[];return grid.slice(1).map(r=>{const title=clean(r[ti]);if(!title)return null;let author=ai>=0?clean(r[ai]):'',date=di>=0?clean(r[di]):'',isbn=ii>=0?clean(r[ii]):'';if(badAuthor(author)){const candidates=r.map(clean);const a=candidates.find(v=>v&&!badAuthor(v)&&v!==title&&!/^\d+$/.test(v));if(a)author=a}if(!date){const d=r.map(clean).find(v=>year(v));if(d)date=d}if(!isbn){const x=r.map(clean).find(v=>/(?:97[89][- ]?)?\d[- 0-9Xx]{8,}/.test(v));if(x)isbn=(x.match(/(?:97[89][- ]?)?\d[- 0-9Xx]{8,}/)||[])[0]||''}const number=ni>=0?Number((clean(r[ni]).match(/\d+/)||[])[0]||0)||null:null;return{title,author:badAuthor(author)?'':author,series:section,number,publicationYear:year(date),isbn}}).filter(Boolean)}
export async function GET(){try{const res=await fetch(WIKI,{headers:{'User-Agent':'StarTrekBooks/1.0'},next:{revalidate:86400}});if(!res.ok)throw new Error(`Wikipedia ${res.status}`);const html=await res.text(),$=cheerio.load(html),books=[];$('table.wikitable').each((_,table)=>{let h=$(table).prevAll('h2,h3,h4').first();const section=clean(h.find('.mw-headline').text()||h.text())||'Uncategorised';books.push(...tableRows($,table,section))});const unique=new Map();for(const b of books){const k=`${b.title.toLowerCase()}|${(b.author||'').toLowerCase()}|${b.publicationYear||''}`;if(!unique.has(k))unique.set(k,b)}let result=[...unique.values()];const sb=createClient(SUPABASE_URL,SUPABASE_KEY);const{data}=await sb.from('goodreads_metadata').select('book_key,goodreads_url,goodreads_rating,goodreads_ratings,fetched_at');const gm=new Map((data||[]).map(x=>[x.book_key,x]));result=result.map(b=>{const k=`${b.title.trim()}|${(b.author||'').trim()}|${b.publicationYear||''}`.toLowerCase(),m=gm.get(k);return{...b,goodreadsUrl:m?.goodreads_url||null,goodreadsRating:m?.goodreads_rating==null?null:Number(m.goodreads_rating),goodreadsRatings:m?.goodreads_ratings??null,goodreadsFetchedAt:m?.fetched_at||null}});return Response.json({books:result,count:result.length,source:'Wikipedia + cached Goodreads metadata'})}catch(e){return Response.json({books:[],count:0,error:e.message},{status:500})}}
